### ISSUE TITLE
Deprecated

### ISSUE THREAD

**Issue by ghost** [Gilgames000/nostale-packet-publisher#1]
Hello Gilgames, 

i already tried your other packet logger and it works really well. I already tried changing it so i can use its messages in another program via pipe, but it seems that i am not possible to even compile the solution correctly. Would it be possible to update the packet publisher?

Greetings Ragon

**Comment by Gilgames000** [comment]
Sorry for the late reply. I will look into the packet publisher as soon as I have some spare time, maybe today. About the packet logger, if you're having any trouble feel free to open an issue on the specific repository. Thanks.

**Comment by Gilgames000** [comment]
@RagonEbker I quickly skimmed through the code and noticed there was an issue which lead to random crashes. It should be fixed now in https://github.com/Gilgames000/nostale-packet-publisher/commit/91abfc05202968d12b6c1212ffde5902d1c2c53f. Please close the issue if the problem you were facing is gone.

Cheers!
